version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: automail-db
    environment:
      POSTGRES_DB: automail-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend FastAPI
  backend:
    build: ./backend
    container_name: automail-backend
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres:5432/automail-db"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  # Frontend React
  frontend:
    build: ./frontend
    container_name: automail-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000

volumes:
  postgres_data: