EXAMPLES = [
    ("Preciso de ajuda para configurar a integração do sistema com outro software que utilizo. Segui o manual de instruções, mas continuo recebendo erros de incompatibilidade. Poderiam me orientar com um passo a passo detalhado?", 0),
    ("Quero agradecer pela pontualidade na entrega do último relatório, ficou excelente e demonstra o comprometimento da equipe.", 1),
    ("Estou muito grato pelo suporte.", 1),
    ("Meu acesso foi bloqueado, como posso desbloquear?", 0 ),
    ("Estou enfrentando erros constantes de autenticação ao tentar acessar via aplicativo mobile. Há alguma atualização disponível para corrigir isso?", 0),
    ("Meu acesso foi bloqueado por excesso de tentativas de login. Como posso redefinir a senha e liberar novamente o acesso?", 0),
    ("Quero elogiar a eficiência dos atendentes.", 1),
    ("Muito obrigado pelo atendimento rápido e eficiente.", 1),
    ("Recebi uma cobrança duplicada, preciso de correção.", 0),
    ("Excelente postura dos profissionais.", 1),
    ("Preciso reativar um serviço que foi cancelado por engano. Podem confirmar se é possível restaurar?", 0),
    ("Solicito desbloqueio de um pagamento retido.", 0),
    ("Preciso atualizar os dados bancários vinculados à minha conta para que os pagamentos sejam realizados corretamente. Poderiam me informar o procedimento?", 0),
    ("Solicito ajuda para baixar a última versão do sistema.", 0),
    ("Parabéns pelo excelente trabalho realizado.", 1),
    ("Estou com problemas para compartilhar arquivos com outros usuários dentro da plataforma. O recurso parece não estar habilitado. Podem verificar?", 0),
    ("Recebi os comunicados recentes e achei todos muito claros e bem estruturados, parabéns à equipe.", 1),
    ("Estou enfrentando problemas para exportar relatórios em formato PDF. O sistema trava sempre que tento realizar essa ação. Podem verificar se há alguma atualização ou correção para isso?", 0),
    ("Muito contente com o atendimento recebido.", 1),
    ("Foi excelente a forma como me atenderam.", 1),
    ("Preciso ativar novamente um contrato suspenso.", 0),
    ("Gostaria de destacar o profissionalismo da equipe.", 1),
    ("Solicito informações sobre a possibilidade de migrar meus dados para um novo ambiente de testes antes de homologar a versão final.", 0),
    ("Gostaria apenas de registrar meu agradecimento pela forma atenciosa com que toda a equipe me atendeu no último contato, não tenho nenhuma pendência ou dúvida no momento, só quis reforçar minha satisfação.", 1),
    ("Excelente experiência que tive com vocês, parabéns.", 1),
    ("Meu login não está funcionando mesmo após redefinir a senha.", 0),
    ("Não preciso de suporte, apenas gostaria de agradecer pela forma ágil com que meu último contato foi tratado.", 1),
    ("Parabéns pela organização da última reunião, foi muito produtiva e bem conduzida.", 1),
    ("Foi uma ótima experiência interagir com a equipe.", 1),
    ("Estou tendo problemas para configurar permissões de administrador na conta da empresa. Preciso de suporte avançado para isso.", 0),
    ("Preciso de ajuda para recuperar arquivos apagados.", 0),
    ("Muito contente com a postura dos atendentes.", 1),
    ("Preciso reativar um usuário que foi desativado.", 0),
    ("O pedido chegou incompleto, como resolver?", 0),
    ("Estou tendo dificuldades para anexar documentos em PDF no sistema. A cada tentativa, recebo um erro dizendo que o formato não é aceito, mesmo estando correto. Preciso de suporte para resolver isso.", 0),
    ("Quero elogiar a paciência dos atendentes.", 1),
    ("Preciso de suporte técnico para configurar o sistema.", 0),
    ("Solicito suporte para instalar em outro dispositivo.", 0),
    ("O sistema está emitindo relatórios em branco, podem corrigir?", 0),
    ("Quero cancelar uma solicitação que abri por engano.", 0),
    ("Solicito atualização da previsão de entrega.", 0),
    ("Solicito suporte para configurar permissões de usuário.", 0),
    ("Gostaria de destacar a simpatia e cordialidade com que fui atendido, fez toda a diferença na minha experiência.", 1),
    ("Preciso reemitir o boleto da última fatura.", 0),
    ("Como faço para consultar meus pedidos anteriores?", 0),
    ("Preciso de ajuda para atualizar a versão do software.", 0),
    ("Preciso de orientações sobre como integrar o sistema com a API que utilizo para faturamento.", 0),
    ("Preciso de auxílio para recuperar uma conta antiga que foi cadastrada com outro e-mail. Podem me orientar no processo de reativação?", 0),
    ("Parabéns pela nova interface, ficou excelente.", 1),
    ("Gostaria de saber se é possível gerar relatórios personalizados com filtros específicos. Se sim, podem me enviar um guia sobre como configurar?", 0),
    ("Excelente serviço prestado, parabéns.", 1),
    ("Agradeço imensamente pela atenção recebida.", 1),
    ("Solicito a atualização do endereço de cobrança cadastrado, pois houve mudança recente.", 0),
    ("Preciso atualizar meu telefone de contato.", 0),
    ("Quero registrar minha satisfação com a forma como minha solicitação anterior foi resolvida.", 1),
    ("Recebi o último boletim informativo e achei de grande qualidade, parabéns a todos os envolvidos.", 1),
    ("Preciso de suporte para criar um novo relatório.", 0),
    ("Quero encerrar meu contrato atual, como proceder?", 0),
    ("Parabéns pela agilidade no suporte prestado.", 1),
    ("Quero alterar a data de vencimento da fatura.", 0),
    ("Solicito a emissão de uma segunda via da fatura do mês passado, pois não recebi o documento original.", 0),
    ("Como faço para mudar minha senha de acesso ao portal?", 0),
    ("Como faço para cancelar meu plano atual?", 0),
    ("Excelente cuidado no atendimento prestado.", 1),
    ("Quero destacar o excelente suporte técnico.", 1),
    ("Solicito ajuda para resetar minha senha.", 0),
    ("Meu cartão foi recusado, como atualizar o pagamento?", 0),
    ("Quero parabenizar a equipe responsável pelo relatório de desempenho trimestral que recebi, o documento está bem estruturado, fácil de entender e cheio de insights valiosos.", 1),
    ("Preciso corrigir o CPF informado na nota fiscal.", 0),
    ("Quero agradecer pela compreensão no meu caso.", 1),
    ("Quero deixar registrado meu elogio à equipe de suporte.", 1),
    ("Muito obrigado pela dedicação demonstrada.", 1),
    ("O sistema não está permitindo a importação de arquivos TXT com meus dados. Preciso de suporte para entender se há um formato específico aceito.", 0),
    ("Quero agradecer pelo ótimo atendimento recebido.", 1),
    ("Gostaria de reconhecer o ótimo trabalho realizado.", 1),
    ("Parabéns pela condução do último projeto, foi entregue com excelência e muito comprometimento.", 1),
    ("Quero saber se o pedido já foi despachado.", 0),
    ("Meu pedido foi entregue no endereço errado.", 0),
    ("Meu acesso foi desativado sem aviso, preciso de retorno.", 0),
    ("Não é necessário retorno, só quero agradecer pelo excelente trabalho realizado até agora.", 1),
    ("Amei o atendimento prestado.", 1),
    ("Muito feliz com a agilidade da equipe.", 1),
    ("O aplicativo fecha sozinho, como resolver?", 0),
    ("Quero destacar o comprometimento da equipe técnica.", 1),
    ("Solicito atualização do endereço na nota fiscal.", 0),
    ("Foi um prazer ser atendido por vocês.", 1),
    ("Obrigado pelo suporte prestado na semana passada.", 1),
    ("Solicito desbloqueio de documentos anexados.", 0),
    ("Quero saber se já existe atualização disponível do software.", 0),
    ("Quero reativar minha assinatura cancelada.", 0),
    ("Muito satisfeito com a dedicação da equipe.", 1),
    ("Parabéns pela qualidade do serviço oferecido!", 1),
    ("Preciso de suporte para sincronizar com o servidor.", 0),
    ("Solicito que corrijam a data de vencimento da minha fatura, que veio incorreta neste mês. O vencimento precisa ser alterado para o dia 15.", 0),
    ("Solicito atualização do prazo de entrega.", 0),
    ("Meu contrato vence este mês, como faço para renová-lo?", 0),
    ("Quero agradecer pela forma gentil do atendimento.", 1),
    ("Quero parabenizar pela qualidade da solução apresentada.", 1),
    ("Parabéns à equipe pelo novo portal de informações, ficou muito intuitivo e agradável de usar.", 1),
    ("Como posso alterar o plano de assinatura atual?", 0),
    ("Fiz uma solicitação de alteração de plano há duas semanas e não tive retorno. Podem confirmar se a mudança foi processada?", 0),
    ("Solicito envio do manual atualizado do sistema.", 0),
    ("Meu relatório não gera os dados corretos, podem verificar?", 0),
    ("Quero elogiar a dedicação da equipe.", 1),
    ("Não preciso de suporte agora, só gostaria de deixar registrado que admiro a forma como a empresa mantém seus processos organizados e transparentes.", 1),
    ("Preciso de ajuda para configurar as notificações por e-mail do sistema. Atualmente não estou recebendo os alertas importantes.", 0),
    ("Quero agradecer pelo carinho no atendimento.", 1),
    ("Solicito suporte para emissão de relatórios financeiros.", 0),
    ("Estou muito feliz com o suporte recebido.", 1),
    ("Solicito envio da última versão do contrato.", 0),
    ("Parabéns pela agilidade no atendimento anterior.", 1),
    ("Escrevo apenas para registrar meu reconhecimento à equipe de atendimento, que sempre me recebe com muita cordialidade e atenção.", 1),
    ("Solicito instruções para emitir relatório detalhado.", 0),
    ("Preciso de suporte para restaurar a configuração original do sistema, pois realizei alterações que não consigo reverter.", 0),
    ("Preciso alterar o responsável financeiro cadastrado na minha conta. Qual é o procedimento?", 0),
    ("Muito satisfeito com o resultado da última interação.", 1),
    ("Excelente resultado no acompanhamento do meu chamado.", 1),
    ("Gostaria de parabenizar o time pela inovação apresentada na última atualização.", 1),
    ("Estou muito grato pela paciência.", 1),
    ("Estou com dificuldades para recuperar arquivos que foram apagados por engano. Existe alguma forma de restaurar os documentos dentro da plataforma? Preciso de suporte técnico para isso.", 0),
    ("Como faço para adicionar mais licenças ao sistema?", 0),
    ("Foi incrível a dedicação de vocês.", 1),
    ("Muito satisfeito com a resposta rápida.", 1),
    ("Parabéns pelo empenho da equipe.", 1),
    ("Excelente acompanhamento realizado no meu caso.", 1),
    ("Não preciso de nenhum suporte agora, apenas gostaria de destacar o excelente trabalho que o time de suporte vem realizando ao longo dos últimos meses, sempre com cordialidade e eficiência.", 1),
    ("Meu pedido foi extraviado, preciso de uma solução.", 0),
    ("Amei a rapidez na resolução do meu problema anterior.", 1),
    ("Excelente postura no acompanhamento.", 1),
    ("Este não é um email de solicitação, mas sim de reconhecimento: estou extremamente satisfeito com o serviço prestado.", 1),
    ("Estou muito satisfeito com a forma que fui atendido.", 1),
    ("Amei a forma como o time conduziu minha solicitação.", 1),
    ("Muito feliz com o cuidado recebido.", 1),
    ("Excelente trabalho realizado na atualização.", 1),
    ("Não tenho dúvidas no momento, apenas gostaria de elogiar a forma como a equipe trata os clientes com respeito e profissionalismo.", 1),
    ("Recebi o manual atualizado e fiquei impressionado com a clareza e detalhamento das instruções, parabéns pelo trabalho.", 1),
    ("Parabéns pelo atendimento de qualidade.", 1),
    ("Obrigado pela atenção e carinho no suporte.", 1),
    ("Foi uma ótima experiência com a equipe.", 1),
    ("Meu pedido ainda não foi entregue, gostaria de uma atualização.", 0),
    ("Quero parabenizar pelo esforço e dedicação da equipe.", 1),
    ("Quero deixar registrado meu reconhecimento pelo ótimo trabalho.", 1),
    ("Estou satisfeito com o retorno que recebi.", 1),
    ("Parabéns pelo ótimo desempenho na última campanha.", 1),
    ("Gostaria de solicitar o desbloqueio da minha conta, que foi suspensa por suspeita de uso indevido. Não recebi nenhuma explicação clara do motivo. Preciso resolver essa situação o quanto antes.", 0),
    ("Quero apenas agradecer pela atenção prestada recentemente, foi um atendimento que fez muita diferença e merece ser reconhecido.", 1),
    ("O suporte foi exemplar, parabéns!", 1),
    ("Meu sistema não atualizou automaticamente, como resolver?", 0),
    ("Preciso de uma cópia do contrato assinado.", 0),
    ("Solicito suporte para configurar integrações via API.", 0),
    ("Parabéns pelo suporte prestado recentemente, resolvi meu problema rapidamente e fui muito bem atendido.", 1),
    ("Ótimo trabalho na entrega realizada, parabéns!", 1),
    ("Gostaria de receber uma demonstração prática de como utilizar o módulo avançado de relatórios, pois não consegui entender apenas com o manual.", 0),
    ("Estou impressionado com a eficiência da equipe.", 1),
    ("Quero parabenizar o time de TI pelo ótimo desempenho na última atualização, o sistema está funcionando perfeitamente.", 1),
    ("Solicito uma cópia digital assinada do contrato atualizado.", 0),
    ("Preciso adicionar novos membros à minha conta empresarial, mas o sistema não permite. Há algum limite no número de usuários? Como proceder para liberar mais acessos?", 0),
    ("Solicito correção do valor lançado na fatura.", 0),
    ("Foi incrível a experiência com vocês.", 1),
    ("Preciso corrigir a data de vencimento do contrato.", 0),
    ("Fiz um pedido na semana passada e até agora não recebi confirmação de envio. Preciso de um retorno com o status da entrega, pois o material é urgente para minha atividade.", 0),
    ("Muito obrigado pelo ótimo suporte.", 1),
    ("Preciso da segunda via da nota fiscal da última compra.", 0),
    ("Preciso alterar o responsável financeiro do contrato.", 0),
    ("Como faço para exportar relatórios do sistema?", 0),
    ("Foi incrível a forma como resolveram meu problema anterior.", 1),
    ("Recebi os relatórios do mês e fiquei impressionado com a qualidade e organização dos dados apresentados.", 1),
    ("Escrevo somente para agradecer pela rapidez com que minha última solicitação foi atendida, fiquei impressionado com a agilidade e profissionalismo da equipe.", 1),
    ("Agradeço pela atenção no meu atendimento.", 1),
    ("Quero saber o status do chamado aberto ontem.", 0),
    ("O sistema não está importando meus dados corretamente.", 0),
    ("Preciso alterar o endereço de entrega de uma encomenda que já está em andamento. O endereço correto é Rua das Flores, nº 120 bairro Centro. Podem confirmar a alteração?", 0),
    ("Estou com dificuldades para acessar arquivos que deveriam estar disponíveis no histórico da minha conta. Podem verificar?", 0),
    ("Solicito suporte para configurar notificações no sistema.", 0),
    ("Como faço para adicionar novos métodos de pagamento?", 0),
    ("O sistema está enviando notificações duplicadas para o meu e-mail. Podem corrigir essa falha?", 0),
    ("Gostaria de ressaltar a excelência no atendimento.", 1),
    ("Preciso atualizar meu endereço de e-mail de contato.", 0),
    ("Não há nenhuma pendência, apenas gostaria de reforçar meu reconhecimento pelo trabalho da equipe.", 1),
    ("Estou encantado com a dedicação da equipe.", 1),
    ("Estou com dificuldades para acessar o sistema desde ontem. Sempre que tento fazer login, aparece uma mensagem de erro dizendo que minhas credenciais são inválidas. Já tentei redefinir a senha, mas não funcionou. Preciso de suporte urgente para conseguir acessar.", 0),
    ("Não consigo acessar minha conta, podem me ajudar?", 0),
    ("Não tenho solicitações neste momento, apenas gostaria de expressar minha satisfação com o desempenho do sistema nos últimos meses.", 1),
    ("Não tenho nenhuma demanda urgente, apenas queria deixar registrado que estou muito contente com a parceria.", 1),
    ("Gostaria de agradecer pelo excelente atendimento prestado.", 1),
    ("Não se trata de um pedido de suporte, mas sim de um elogio sincero: fiquei muito satisfeito com a forma como fui tratado na última reunião, todos muito atenciosos e competentes.", 1),
    ("Este email é apenas para reforçar meu reconhecimento ao time de desenvolvimento, que vem entregando funcionalidades que realmente fazem diferença na rotina de quem usa o sistema diariamente.", 1),
    ("Estou muito grato pelo acompanhamento.", 1),
    ("Meu acesso expira hoje, como renovar?", 0),
    ("Como faço para cancelar uma compra feita por engano?", 0),
    ("Meu cadastro foi suspenso, como regularizar?", 0),
    ("Quero agradecer a presteza no atendimento.", 1),
    ("Há divergências no saldo apresentado no sistema em comparação com meu extrato bancário. Podem verificar e corrigir?", 0),
    ("Percebi que a fatura do mês passado veio com valores incorretos. Consta uma cobrança duplicada de um serviço que não solicitei. Peço a gentileza de verificar e corrigir a cobrança, além de emitir a nota fiscal revisada.", 0),
    ("Estou enfrentando dificuldades para anexar múltiplos arquivos em um mesmo chamado. Existe alguma limitação?", 0),
    ("A senha temporária não funcionou, podem gerar outra?", 0),
    ("Não preciso de suporte agora, só queria agradecer pela eficiência do time de atendimento.", 1),
    ("Este contato é apenas para parabenizar pela organização do último evento online, foi muito proveitoso e bem estruturado.", 1),
    ("Solicito suporte para instalação em um novo computador.", 0),
    ("Fiz a instalação do software em três máquinas, mas apenas em uma delas está funcionando corretamente. Nas outras, recebo erro de inicialização. Preciso de ajuda para corrigir isso.", 0),
    ("Quero alterar a forma de pagamento da minha assinatura.", 0),
    ("Quero agradecer pela atenção ao meu caso anterior.", 1),
    ("Quero migrar para um plano superior, como faço?", 0),
    ("Gostaria de solicitar o cancelamento imediato da assinatura, visto que não irei mais utilizar o sistema. Peço também que confirmem a data de encerramento e enviem o comprovante.", 0),
    ("Estou extremamente satisfeito com a atenção recebida.", 1),
    ("Recebi um comunicado de que meu cadastro está incompleto. Poderiam me informar exatamente quais documentos faltam para que eu possa enviar e regularizar minha situação?", 0),
    ("Não tenho nenhuma pendência, apenas queria elogiar a disponibilidade e atenção do suporte.", 1),
    ("Parabéns pelo profissionalismo demonstrado.", 1),
    ("Solicito suporte para configurar relatórios automáticos.", 0),
    ("Obrigado por todo o apoio dado anteriormente.", 1),
    ("Excelente postura profissional do time de atendimento.", 1),
    ("Não tenho nenhuma dúvida, apenas gostaria de elogiar o empenho do time de suporte técnico.", 1),
    ("Solicito informações sobre o andamento do meu chamado.", 0),
    ("Meu relatório está apresentando números incorretos.", 0),
    ("Recebi a última atualização do sistema e queria parabenizar pelo trabalho, ficou mais rápido e estável, estou muito satisfeito.", 1),
    ("Quero cancelar uma cobrança indevida.", 0),
    ("Como faço para transferir a titularidade da conta?", 0),
    ("Este email é apenas para expressar meu reconhecimento pela eficiência no processo de atendimento, não tenho nada a solicitar.", 1),
    ("Quero elogiar a competência dos profissionais.", 1),
    ("Preciso corrigir um erro cadastral urgente.", 0),
    ("Foi uma experiência muito positiva, parabéns.", 1),
    ("Não é um pedido, mas sim um reconhecimento: a equipe de suporte está cada vez mais eficiente, parabéns.", 1),
    ("Solicito que enviem novamente o contrato atualizado do serviço, pois não encontrei o documento no meu e-mail e preciso arquivá-lo.", 0),
    ("Gostaria de destacar o excelente atendimento.", 1),
    ("Solicito status da minha solicitação de reembolso.", 0),
    ("Não tenho dúvidas ou solicitações, mas gostaria de elogiar o design da nova área do cliente, ficou realmente muito moderno e prático.", 1),
    ("Estou impressionado com a melhoria do sistema.", 1),
    ("Preciso corrigir dados do cartão cadastrado.", 0),
    ("Solicito que revisem os relatórios de desempenho que recebi no último mês. Identifiquei divergências entre os dados apresentados e os números que registrei internamente.", 0),
    ("Solicito informações detalhadas sobre a política de reembolso em caso de cancelamento do serviço. Preciso entender prazos, valores e como funciona o processo.", 0),
    ("Como posso emitir a segunda via do contrato?", 0),
    ("Preciso confirmar se meu pagamento foi recebido, pois o status ainda aparece como pendente no sistema.", 0),
    ("Este email é apenas para registrar minha satisfação com a experiência de atendimento.", 1),
    ("Estou escrevendo apenas para compartilhar minha satisfação com a campanha realizada pela empresa, o material enviado foi de excelente qualidade e realmente passou confiança.", 1),
    ("Quero agradecer imensamente pelo apoio recebido.", 1),
    ("Solicito a troca do endereço de entrega.", 0),
    ("Preciso de um treinamento rápido para usar a nova função.", 0),
    ("Preciso de ajuda para configurar alertas automáticos.", 0),
    ("Este email não é para solicitar nada, apenas para agradecer pelo ótimo atendimento que venho recebendo desde que iniciei a parceria com vocês.", 1),
    ("Solicito suporte para corrigir o erro de sincronização entre a plataforma e meu calendário externo. Os eventos não estão aparecendo corretamente.", 0),
]
